### ISSUE TITLE
Opening the driver file twice causes undefined behaviour and crashes

### ISSUE THREAD

**Issue by CiaranWoodward** [Cascoda/ca8210-linux#2]
Opening the driver file twice causes undefined behaviour and crashes.

It is probably worth throwing some sort of error to the user application if the driver is attempted to be opened a second time. Current behaviour would render each user application unuseable and renders the system unstable.

**Comment by HarryMorris** [comment]
Issue should be fixed by https://github.com/Cascoda/ca8210-linux/commit/c6abddd346c745972ee6c5a2d796f95232a6d8db
